language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

cache: pip

env:
  - EMG_CONFIG=$TRAVIS_BUILD_DIR/travis/configuration.yaml

services:
  - mysql
  - mongodb

before_install:
  - mysql -e 'CREATE DATABASE emg;'
  - mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES'"
  - python -V

install:
  - pip install -U git+git://github.com/EBI-Metagenomics/emg-backlog-schema.git
  - pip install -U git+git://github.com/EBI-Metagenomics/ena-api-handler.git
  - pip install -U -r requirements-test.txt
  - pip install "flake8==3.4" "pycodestyle==2.3.1" pep8-naming
  - pip install "git+git://github.com/EBI-Metagenomics/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - python setup.py sdist

script:
  - pip install -U .
  - pip freeze
  - python setup.py test

after_script:
  - flake8 --version
  - flake8 -v .

notifications:
  slack:
    secure: WMsDqF0FIwNEpTANi7bHHYLNgONOuwmgUheKlr2cZ3DT34xzfRvuH7BhpOJJ+Cxb3oKa/c18KZeKS1MZF2oxy3mnI9Vdzwv6nBem9DCm8iP4ax6ZwhXUDaPEo0U+RECLgzew7tJRv+tqDQdjl/QJA8PLJyo3jfg5Yb35Mgs29urMVDdXL/POSZ4EV+jfZ/PavocXXK6d9n+K8OvnvWt7yon/lPeajpmHd+CC8gRRZaXb7im+z6N3iIkWSjtorAYAiXMSfvfuouIoCRIWuwkJBpK1EdC4FQx09UE2Yne3r6gxrdVpMjwvxGOwbLF4kt5i8jAvPUS1vXk/xrMibWia38fuFZjeWbqXUbS+YXv7O6hVzcYtwQNjn+0dsSsikUE4AqYn1MH4FTVaBCDUUfOBfwYhUKZAQMI+eTpH/s335ChMHNj7X4/DAkl2lMlMQiuo1kjQmTbgAwprNcR5gJtxuyRApcLJDGPKAWd5Mraq/m+Dk0CerDXmqiUTNWONLZRh5KvEKz05Mm1YeUN/0CRNpc3N2jC9J2jCXkBiGTiv0eiTFbtKd7kQe6hpKdIl2EUVeIIjvmPCy1/SKqZHhoXlPs4f8P1xknSOkhjpOMjcKnCiLgYj250Z061VU1dz0iuPHltL628F87WABAhgnP9nc7owGSwKollhTUywxRMLODY=
